robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  

  # Effort Controllers ---------------------------------------
  frontleftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

  backleftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

  backrightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_back_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}

  frontrightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_front_wheel_hinge
    pid: {p: 100.0, i: 0.1, d: 10.0}


  





